% Split Yeo7 thalamus ROIs by hemisphere

V = spm_vol('../Yeo-thalamus/1000subjects_TightThalamus_clusters007_ref.nii.gz');
[Y,XYZ] = spm_read_vols(V);

lh = XYZ(1,:)<=0;
rh = XYZ(1,:)>=0;

Yl = Y;
Yl(rh) = 0;
Yl(Yl(:)>0) = Yl(Yl(:)>0) + 10;

Yr = Y;
Yr(lh) = 0;
Yr(Yr(:)>0) = Yr(Yr(:)>0) + 20;

Yout = Yl + Yr;

Vout = rmfield(V,{'private','dat'});
Vout.fname = 'yeo7_thalamus_lr.nii';

spm_write_vol(Vout,Yout);
system('gzip -f yeo7_thalamus_lr.nii');

Label = [11:17 21:27]';
Region = { ...
    'yeo7_1_l', ...
    'yeo7_2_l', ...
    'yeo7_3_l', ...
    'yeo7_4_l', ...
    'yeo7_5_l', ...
    'yeo7_6_l', ...
    'yeo7_7_l', ...
    'yeo7_1_r', ...
    'yeo7_2_r', ...
    'yeo7_3_r', ...
    'yeo7_4_r', ...
    'yeo7_5_r', ...
    'yeo7_6_r', ...
    'yeo7_7_r' ...
    }';
Network = { ...
    'Vis', ...
    'SomMot', ...
    'DorsAttn', ...
    'SalVentAttn', ...
    'Limbic', ...
    'Cont', ...
    'Default', ...
    'Vis', ...
    'SomMot', ...
    'DorsAttn', ...
    'SalVentAttn', ...
    'Limbic', ...
    'Cont', ...
    'Default' ...
    }';
NetworkNum = [1;2;3;4;5;6;7;1;2;3;4;5;6;7];

info = table(Label,Region,Network,NetworkNum);
writetable(info,'yeo7_thalamus_lr-labels.csv');

