% Split Yeo7 thalamus ROIs by hemisphere

V = spm_vol('../Yeo-thalamus/1000subjects_TightThalamus_clusters007_ref.nii.gz');
[Y,XYZ] = spm_read_vols(V);

lh = XYZ(1,:)<=0;
rh = XYZ(1,:)>=0;

Yl = Y;
Yl(rh) = 0;
Yl(Yl(:)>0) = Yl(Yl(:)>0) + 10;

Yr = Y;
Yr(lh) = 0;
Yr(Yr(:)>0) = Yr(Yr(:)>0) + 20;

Yout = Yl + Yr;

Vout = rmfield(V,{'private','dat'});
Vout.fname = 'Yeo7_thalamus_LR.nii';

spm_write_vol(Vout,Yout);
system('gzip -f Yeo7_thalamus_LR.nii');

Label = [11:17 21:27]';
Region = { ...
    'Yeo7_1_L', ...
    'Yeo7_2_L', ...
    'Yeo7_3_L', ...
    'Yeo7_4_L', ...
    'Yeo7_5_L', ...
    'Yeo7_6_L', ...
    'Yeo7_7_L', ...
    'Yeo7_1_R', ...
    'Yeo7_2_R', ...
    'Yeo7_3_R', ...
    'Yeo7_4_R', ...
    'Yeo7_5_R', ...
    'Yeo7_6_R', ...
    'Yeo7_7_R' ...
    }';
info = table(Label,Region);
writetable(info,'Yeo7_thalamus_LR-labels.csv');

