function compute_connmat(roi_csv1,roi_csv2,out_dir,out_basename)

roi_data1 = readtable(roi_csv1);
roi_data2 = readtable(roi_csv2);

R = corr(table2array(roi_data1),table2array(roi_data2));
Z = atanh(R) .* sqrt(size(roi_data1,1)-3);

R = array2table( ...
    R, ...
    'VariableNames',roi_data2.Properties.VariableNames(:), ...
    'RowNames',roi_data1.Properties.VariableNames(:) ...
    );

Z = array2table( ...
    Z, ...
    'VariableNames',roi_data2.Properties.VariableNames(:), ...
    'RowNames',roi_data1.Properties.VariableNames(:) ...
    );

writetable(R,fullfile(out_dir,['R_' out_basename '.csv']),'WriteRowNames',true)
writetable(Z,fullfile(out_dir,['Z_' out_basename '.csv']),'WriteRowNames',true)

